schema_version: 1

context:
  name: pelicanplatform
  version: "7.26.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/PelicanPlatform/pelican/archive/v${{ version }}.tar.gz
    sha256: 27e236615895c7c729de0d8e21dd31af98fbcdb3a4933273d9bbacad62a36104
  - url: https://gitlab.com/cznic/mathutil/-/raw/v1.5.0/LICENSE
    sha256: bfa9bf72a72ca009fd62a8f84fca3dca67e51d93af96352723646599898b6cf5
    file_name: LICENSE-mathutil
  - url: https://raw.githubusercontent.com/jmespath/go-jmespath/refs/tags/v0.4.0/LICENSE
    sha256: 03cfaf331a260694d06227a589cdd2b5fcfab474697b72e250736696c313655a
    file_name: LICENSE-jmespath
  - url: https://raw.githubusercontent.com/open-telemetry/opentelemetry-go/refs/tags/v1.43.0/LICENSE
    sha256: 1ae07514be1d7bb33f0698f8d91fb51b8b9fe1463157ec1c72081a49b9bc6f40
    file_name: LICENSE-opentelemetry

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go') }}
    - go-licenses

tests:
  - script:
      - pelican --help
      - pelican --version
      - if: unix
        then: "pelican --version | grep -q 'Version: ${{ version }}'"
      - pelican object copy --help

about:
  summary: The Pelican command line tool
  description: |
    The Pelican command line tool allows one to use a Pelican federation as
    a client and serve datasets through running a Pelican origin service.
  homepage: https://github.com/PelicanPlatform/pelican
  repository: https://github.com/PelicanPlatform/pelican
  license: Apache-2.0
  license_file:
    - LICENSE
    - LICENSE-jmespath
    - LICENSE-mathutil
    - LICENSE-opentelemetry
    - license-files/

extra:
  recipe-maintainers:
    - duncanmmacleod
    - turetske
